version: 2.1

command:
   destroy_environment:
    steps:
      - run:
         name: Destroy environment
         command: |
          aws cloudformation delete-stack --stack-name 	my-stack-4

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: return 1
      - destroy_environment
          when: on_fail

 
workflows:
  my_workflow:
    jobs:
      - configure_infrastructure