version: 2.1

jobs:
  my_job:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: execute template
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack_2


workflows:
  my_workflow:
    jobs:
      - my_job